name: CI/CD

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'dev' # or: 'dev' or 'beta'
    - name: Build Flutter web
      run: | 
        flutter pub get
        flutter upgrade
        flutter config --enable-web
        flutter build web
    - name: Install node  
      run: |
        npm install
        npm run build
    - name: Firebase Deploy
      run: |
        sudo npm install -g firebase-tools
        firebase use dev
        firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
            
      
