name: Dart CI

on:
  push:
    branches: [ stage ]
  pull_request:
    branches: [ stage ]

jobs: 
  build-and-test: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1 
    # The flutter action needs java so include it
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    # Include the flutter action
    - uses: subosito/flutter-action@v1
      with:
        channel: 'beta'  
    - run: |+
          cat >~/.netrc <<EOF
          machine api.heroku.com
              login ${{ secrets.HEROKU_EMAIL }}
              password ${{ secrets.HEROKU_API_KEY }}
          machine git.heroku.com
              login ${{ secrets.HEROKU_EMAIL }}
              password ${{ secrets.HEROKU_API_KEY }}
          EOF
    - run: heroku login      
    - run: heroku container:login 
    - run: heroku container:push web --app whiteboard-fe
    - run: heroku container:release web --app whiteboard-fe
